import { useEffect, useMemo, useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { CameraView, useCameraPermissions } from 'expo-camera';
import QRCode from 'react-native-qrcode-svg';
import { useRouter } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { buildSyncPayload, loadResources, mergePayload, saveResources } from '@/lib/firefly';
import { colors } from '@/lib/theme';
import type { FireflyResource } from '@/lib/types';

export default function FireflySync(){
 const router=useRouter(); const [resources,setResources]=useState<FireflyResource[]>([]); const [mode,setMode]=useState<'share'|'scan'>('share'); const [permission,requestPermission]=useCameraPermissions(); const [message,setMessage]=useState('');
 useEffect(()=>{loadResources().then(setResources)},[]); const payload=useMemo(()=>buildSyncPayload(resources),[resources]);
 async function scanned(raw:string){ try{const merged=mergePayload(resources,raw);await saveResources(merged);setResources(merged);setMessage(`Synced ${merged.length} resource records.`);setMode('share')}catch{setMessage('That was not a valid Firefly code.')}}
 return <View style={s.page}><View style={s.top}><Pressable onPress={()=>router.back()} style={s.back}><Ionicons name="arrow-back" size={21} color={colors.firefly}/></Pressable><Text style={s.brand}>FIREFLY SYNC</Text><View style={{width:42}}/></View>
  <Text style={s.title}>{mode==='share'?'Let another phone learn what yours knows.':'Point at another Firefly code.'}</Text>
  <View style={s.switch}><Pressable onPress={()=>setMode('share')} style={[s.switchBtn,mode==='share'&&s.switchOn]}><Text style={[s.switchT,mode==='share'&&s.switchTOn]}>SHARE</Text></Pressable><Pressable onPress={async()=>{if(!permission?.granted)await requestPermission();setMode('scan')}} style={[s.switchBtn,mode==='scan'&&s.switchOn]}><Text style={[s.switchT,mode==='scan'&&s.switchTOn]}>SCAN</Text></Pressable></View>
  <View style={s.stage}>{mode==='share'?<View style={s.qrWrap}><QRCode value={payload||'{}'} size={235} color={colors.fireflyBg} backgroundColor={colors.firefly}/><View style={s.spark}/></View>:permission?.granted?<CameraView style={s.camera} barcodeScannerSettings={{barcodeTypes:['qr']}} onBarcodeScanned={({data})=>scanned(data)}><View style={s.frame}/></CameraView>:<Pressable onPress={requestPermission} style={s.permission}><Text style={s.permissionText}>Allow camera to scan Firefly codes</Text></Pressable>}</View>
  <Text style={s.count}>{resources.length} cached resource records · QR generated locally</Text>{message?<Text style={s.message}>{message}</Text>:null}
  <View style={s.note}><Ionicons name="swap-horizontal" size={19} color={colors.firefly}/><Text style={s.noteT}>No account handshake is needed for the QR exchange. The receiver merges newer, higher-confidence resource records into its own local cache.</Text></View>
 </View>
}
const s=StyleSheet.create({page:{flex:1,backgroundColor:colors.fireflyBg,padding:18,paddingTop:55},top:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},back:{width:42,height:42,borderRadius:21,borderWidth:1,borderColor:'#2A342E',alignItems:'center',justifyContent:'center'},brand:{fontFamily:'DMSans_700Bold',fontSize:11,letterSpacing:2,color:colors.firefly},title:{fontFamily:'Fraunces_700Bold',fontSize:34,lineHeight:38,color:'#F3F5EF',marginTop:30},switch:{flexDirection:'row',backgroundColor:'#151C18',borderRadius:15,padding:4,marginTop:20},switchBtn:{flex:1,paddingVertical:11,alignItems:'center',borderRadius:12},switchOn:{backgroundColor:colors.firefly},switchT:{fontFamily:'DMSans_700Bold',fontSize:10,letterSpacing:1.5,color:'#7D8A82'},switchTOn:{color:colors.fireflyBg},stage:{height:350,alignItems:'center',justifyContent:'center',marginTop:20},qrWrap:{padding:22,backgroundColor:colors.firefly,borderRadius:30,shadowColor:colors.firefly,shadowOpacity:.25,shadowRadius:28},spark:{position:'absolute',right:-7,top:40,width:13,height:13,borderRadius:7,backgroundColor:colors.firefly,shadowColor:colors.firefly,shadowOpacity:1,shadowRadius:16},camera:{width:'100%',height:330,borderRadius:26,overflow:'hidden',alignItems:'center',justifyContent:'center'},frame:{width:230,height:230,borderWidth:2,borderColor:colors.firefly,borderRadius:26},permission:{backgroundColor:colors.firefly,padding:18,borderRadius:16},permissionText:{fontFamily:'DMSans_700Bold',color:colors.fireflyBg},count:{fontFamily:'DMSans_500Medium',fontSize:11,color:'#75827A',textAlign:'center'},message:{fontFamily:'DMSans_700Bold',fontSize:12,color:colors.firefly,textAlign:'center',marginTop:10},note:{marginTop:20,flexDirection:'row',gap:10,padding:15,borderWidth:1,borderColor:'#263029',borderRadius:18},noteT:{flex:1,fontFamily:'DMSans_400Regular',fontSize:12,lineHeight:19,color:'#8B978F'}});
